// This file is auto-generated by @hey-api/openapi-ts

export const $Body_GeneratePost = {
    properties: {
        images: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Images'
        },
        user_input: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Input'
        }
    },
    type: 'object',
    required: ['images'],
    title: 'Body_GeneratePost'
} as const;

export const $GeneratedPost = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        hashtags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Hashtags'
        }
    },
    type: 'object',
    required: ['title', 'description', 'hashtags'],
    title: 'GeneratedPost'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $PostGenerationResponse = {
    properties: {
        post: {
            '$ref': '#/components/schemas/GeneratedPost'
        },
        image_count: {
            type: 'integer',
            title: 'Image Count'
        },
        total_cost: {
            type: 'number',
            title: 'Total Cost'
        },
        image_processing_cost: {
            type: 'number',
            title: 'Image Processing Cost'
        },
        post_generation_cost: {
            type: 'number',
            title: 'Post Generation Cost'
        },
        timing_info: {
            additionalProperties: {
                type: 'number'
            },
            type: 'object',
            title: 'Timing Info'
        }
    },
    type: 'object',
    required: ['post', 'image_count', 'total_cost', 'image_processing_cost', 'post_generation_cost', 'timing_info'],
    title: 'PostGenerationResponse'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;