// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GeneratePostData, GeneratePostResponse } from './types.gen';

/**
 * Generate Post
 * @param data The data for the request.
 * @param data.formData
 * @returns PostGenerationResponse Successful Response
 * @throws ApiError
 */
export const generatePost = (data: GeneratePostData): CancelablePromise<GeneratePostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/v1/generate-post/',
    formData: data.formData,
    mediaType: 'multipart/form-data',
    errors: {
        422: 'Validation Error'
    }
}); };