# Generated by Django 2.2.2 on 2019-06-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('const', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date create')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
