# Generated by Django 2.2.2 on 2019-07-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curbd_app', '0002_auto_20190701_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='const',
            new_name='price',
        ),
    ]
